export const Films =[
    {
      id: 1, 
      title: 'Fast & Furious X', 
      year: '19/5/2023', 
      nation:'USA', 
      img:'assets/imagesfilms/FastX.jpg',
      like: '527',
      director:'Louis Leterrier',
      performer:'Vin Diesel, Jason Momoa, Brie Larson,...',
      category:'Hành Động',
      time:'141 phút',
      rated:'16+',
      video:'https://www.youtube.com/watch?v=32RAq6JzY-w',
      titleVideo:'Trailer Film',
      description:' Fast & Furious X (tiếng Anh: Fast X) là một bộ phim điện ảnh Mỹ thuộc thể loại hành động công chiếu vào năm 2023. Là phần hậu truyện của Fast & Furious 9: Huyền thoại tốc độ (2021), phần phim thứ 10 trong mạch truyện chính, và là phần phim thứ 11 trong loạt phim Fast & Furious nói chung. Trong phần Fast & Furious X Dominic Toretto phải bảo vệ phi hành đoàn và gia đình của mình khỏi Cipher, người hiện đang gia nhập lực lượng với Dante, con trai của trùm ma túy Hernan Reyes, tìm cách trả thù cho cái chết của cha mình.'
    },
    {
      id: 2, 
      title: 'Avergenrs ENDGAME', 
      year: '26/4/2019', 
      nation:'USA', 
      img:'assets/imagesfilms/Avengers.jpg',
      like: '5046',
      director:'Anthony Russo, Joe Russo',
      performer:'Robert Downey Jr., Chris Evans, Chris Hemsworth, Scarlett Johansson,...',
      category:'Hành Động, Khoa Học Viễn Tưởng',
      time:'181 phút',
      rated:'16+',
      video:'https://www.youtube.com/watch?v=TcMBFSGVi1c',
      titleVideo:'Trailer Film',
      description:' Avengers: Hồi kết (tựa gốc tiếng Anh: Avengers: Endgame) là phần thứ tư của loạt phim Avengers do Marvel Studios sản xuất. Trong phim, các thành viên còn sống sót của nhóm Avengers cùng các đồng minh hợp tác với nhau để đảo ngược lại những hậu quả mà Thanos đã gây ra trong Avengers: Cuộc chiến vô cực.'
    },
    {
      id: 3, 
      title: 'IP Man', 
      year: '18/12/2008', 
      nation:'Hong Kong', 
      img:'assets/imagesfilms/IpMan.jpg',
      like: '705',
      director:'Wilson Yip',
      performer:'Donnie Yen, Simon Yam, Lynn Hung,...',
      category:'Hành Động',
      time:'108 phút',
      rated:'16+',
      video:'https://www.youtube.com/watch?v=RBYbqO_FUA4',
      titleVideo:'Trailer Film',
      description:'Ip Man là một bộ phim võ thuật tiểu sử của Hồng Kông năm 2008dựa trên cuộc đời của Ip Man , một kiện tướng của môn võ Vịnh Xuân Quyền và là thầy của Lý Tiểu Long. Bộ phim tập trung vào các sự kiện trong cuộc đời của Ip được cho là diễn ra tại thành phố Phật Sơn trong Chiến tranh Trung-Nhật.'
    },
    {
      id: 4, 
      title:'Jurassic World', 
      year:'12/6/2015', 
      nation:'USA', 
      img:'assets/imagesfilms/JurassicWorld.jpg',
      like: '236',
      director:'Colin Trevorrow',
      performer:'Chris Pratt, Bryce Dallas Howard, Jake Johnson,...',
      category:'Hành Động, Khoa Học Viễn Tưởng',
      time:'124 phút',
      rated:'16+',
      video:'https://www.youtube.com/watch?v=RFinNxS5KN4',
      titleVideo:'Trailer Film',
      description:'Thế giới khủng long (tựa gốc tiếng Anh: Jurassic World) là phần thứ tư của dòng phim Công viên kỷ Jura. Một công viên chủ đề mới, được xây dựng trên địa điểm ban đầu của Công viên kỷ Jura, tạo ra một loài khủng long lai biến đổi gen, Indominus Rex, thoát khỏi sự quản thúc và lao vào một cuộc giết chóc.'
    },
    {
      id: 5, 
      title: 'Minion', 
      year: '1/7/2022', 
      nation:'USA', 
      img:'assets/imagesfilms/Minions.jpg',
      like: '1267',
      director:'Kyle Balda',
      performer:'Steve Carell, Pierre Coffin, JTaraji P. Henson,...',
      category:'Hoạt Hình, Phiêu Lưu',
      time:'88 phút',
      rated:'10+',
      video:'https://www.youtube.com/watch?v=dTQXlDV16SY',
      titleVideo:'Trailer Film',
      description:'Minions: Sự trỗi dậy của Gru (tựa gốc tiếng Anh: Minions: The Rise of Gru) là một bộ phim hoạt hình máy tính hài của Mỹ năm 2022. Sự Trỗi Dậy Của Gru là câu chuyện rất lâu trước khi trở thành một phản diện chuyên nghiệp, Gru chỉ là một cậu bé 12 tuổi sống ở vùng ngoại ô vào những năm 1970, với ước mơ một ngày sẽ làm “bá chủ” thế giới. Và 3 “Minion” vàng biết đi từ trên trời rơi xuống đã là những đồng đội đầu tiên của Gru, bên cạnh ủng hộ cậu bé, cùng nhau thiết kế những vũ khí đầu tiên, thực hiện những phi vụ đầu tiên.'
    },
    {
      id: 6, 
      title: 'Parasite', 
      year: '30/5/2019', 
      nation:'Korea', 
      img:'assets/imagesfilms/Parasite.jpg',
      like: '3057',
      director:'Bong Joon-ho',
      performer:'Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong, Park So-dam,...',
      category:'Tâm Lí Xã Hội',
      time:'132 phút',
      rated:'16+',
      video:'https://www.youtube.com/watch?v=isOGD_7hNIY',
      titleVideo:'Trailer Film',
      description:'Ký sinh trùng (tiếng Anh: Parasite) à một bộ phim điện ảnh Hàn Quốc thuộc thể loại hài đen – giật gân – chính kịch. Câu chuyện xoay quanh hai gia đình hoàn toàn trái ngược: một bên vô cùng giàu có, còn một bên luôn sống trong cảnh nghèo túng. Họ tình cờ gặp gỡ và quen biết nhau sau một biến cố không ngờ.'
    },
    {
      id: 7, 
      title: 'Transfomers', 
      year: '27/6/2014', 
      nation:'USA', 
      img:'assets/imagesfilms/Transformers.jpg',
      like: '1050',
      director:'Ehren Kruger',
      performer:'Mark Wahlberg, Stanley Tucci, Kelsey Grammer,...',
      category:'Hành Động, Khoa Học Viễn Tưởng',
      time:'165 phút',
      rated:'16+',
      video:'https://www.youtube.com/watch?v=T9bQCAWahLk',
      titleVideo:'Trailer Film',
      description:'Transformers: Kỷ nguyên hủy diệt (tựa tiếng Anh là Transformers: Age of Extinction) là một bộ phim 3D hành động khoa học viễn tưởng năm 2014 thuộc sản phẩm thương mại Transformers. Đây là phần thứ tư của loạt phim đình đám Transformers. Kỷ Nguyên Huỷ Diệt bắt đầu sau một trận chiến lịch sử để lại một thành phố đổ nát. Với những mảnh ghép còn xót lại, một nhóm những robot cho thấy khả năng của họ có khả năng thay đổi lịch sử. Dẫn đầu nhóm autorobot là Optimus Prime chiến đấu với Dinobot, một cuộc chiến giữa thiện và ác.'
    },
    {
      id: 8, 
      title: 'YourName', 
      year: '26/8/2016', 
      nation:'Japan', 
      img:'assets/imagesfilms/YourName.jpg',
      like: '854',
      director:'Shinkai Makoto',
      performer:'Kamiki Ryunosuke, Kamishiraishi Mone',
      category:'Hoạt Hình, Tình Cảm, Kỳ Ảo',
      time:'107 phút',
      rated:'13+',
      video:'https://www.youtube.com/watch?v=_mifHzxFNQ4',
      titleVideo:'Trailer Film',
      description:'Your Name – Tên cậu là gì? là một bộ phim điện ảnh hoạt hình Nhật Bản. Phim kể về Mitsuha – nữ sinh trung học sống ở một thị trấn nhỏ của vùng Itomori. Luôn chán chường với cuộc sống tẻ nhạt ở vùng thôn quê, Mitsuha ao ước kiếp sau được làm một anh chàng đẹp trai sống ở thủ đô Tokyo sôi động. Trong khi đó ở Tokyo, anh chàng Taki rất hài lòng với cuộc sống và công việc làm thêm ở một nhà hàng Italy sau giờ học. Tuy vậy, hằng đêm cậu vẫn mơ thấy mình trong cơ thể một cô gái thôn quê. Đến một hôm khi sự kiện nghìn năm có một là Sao Chổi tiến gần tới Trái đất, Taki và Mitsuha bỗng bị hoán đổi cơ thể.'
    },
    {
      id: 9, 
      title: 'Big Hero 6', 
      year: '17/11/2014', 
      nation:'USA', 
      img:'assets/imagesfilms/BigHero6.jpg',
      like: '1160',
      director:'Don Hall, Chris Williams',
      performer:'Ryan Potter, Scott Adsit, Jamie Chung,...',
      category:'Hoạt Hình, Tình Cảm, Kỳ Ảo',
      time:'107 phút',
      rated:'13+',
      video:'https://www.youtube.com/watch?v=z3biFxZIJOQ',
      titleVideo:'Trailer Film',
      description:'Biệt Đội Big Hero 6  là một bộ phim 3D siêu anh hùng được hoạt hình bằng máy tính của hãng Walt Disney Animation Studios. Big Hero 6 là câu chuyện kể về cậu bé 14 tuổi đã tốt nghiệp Trung học -Hiro Hamada (lồng tiếng bởi Ryan Potter) tại thành phố San Fransokyo viễn tưởng, cùng với biệt đội siêu anh hùng Big Hero 6, họ lên hành trình đi tìm tên siêu phản diện đứng đằng sau vụ hỏa hoạn dẫn đến cái chết của người anh trai Tadashi.'
    },
    {
      id: 10, 
      title: 'Searching', 
      year: '24/8/2018', 
      nation:'USA', 
      img:'assets/imagesfilms/Searching.jpg',
      like: '1587',
      director:'Aneesh Chaganty',
      performer:'John Cho, Debra Messing,...',
      category:'Tâm Lí, Bí Ẩn',
      time:'102 phút',
      rated:'16+',
      video:'https://www.youtube.com/watch?v=0GTdqfIvFGQ',
      titleVideo:'Trailer Film',
      description:'Searching là một bộ phim kinh dị bí ẩn về cuộc sống trên màn ảnh của Mỹ năm 2018. Truy Tìm Tung Tích Ảo là câu truyện về 37 tiếng sau khi con gái mất tích, ông bố David Kim quyết định tự mình điều tra sự thật. Đến lúc này, ông bàng hoàng nhận ra một điều rằng: Hóa ra từ trước đến nay ông không hề hiểu gì về cuộc sống của cô con gái 16 tuổi cả.'
    },
    {
      id: 11, 
      title: 'The MATRIX', 
      year: '8/4/2000', 
      nation:'USA', 
      img:'assets/imagesfilms/Matrix.jpg',
      like: '459',
      director:'Aneesh Chaganty',
      performer:'Lana Wachowski, Lilly Wachowski',
      category:'Hành Động, Khoa Học Viễn Tưởng',
      time:'136 phút',
      rated:'16+',
      video:'https://www.youtube.com/watch?v=vKQi3bBA1y8',
      titleVideo:'Trailer Film',
      description:'Trong phim Ma Trận, một lập trình viên tên Thomas A. Anderson (Keanu Reeves) trong một công ty điện toán còn là một hacker với biệt danh Neo. Neo thường đột nhập vào các hệ thống an ninh mạng, sau nhiều lần như thế, anh gặp gỡ một nhóm hacker bí ẩn. Họ thường giới thiệu với anh về một thuật ngữ: Ma trận. Thủ lĩnh của nhóm này là Morpheus (Laurence Fishburne), người hứa sẽ cho anh cơ hội để tìm ra sự thật về thế giới mà anh đang sống.'
    },
    {
      id: 12, 
      title: 'Lật Mặt 6', 
      year: '28/4/2023', 
      nation:'Việt Nam', 
      img:'assets/imagesfilms/LatMat6.jpg',
      like: '2589',
      director:'Lý Hải',
      performer:'Trung Dũng, Quốc Cường, Quỳnh Như, Huy Khánh',
      category:'Hành Động, Khoa Học Viễn Tưởng',
      time:'132 phút',
      rated:'16+',
      video:'https://www.youtube.com/watch?v=2EnP2tVC00Q',
      titleVideo:'Trailer Film',
      description:'Một nhóm bạn thân lâu năm bất ngờ nhận được cơ hội đổi đời khi biết tấm vé của cả nhóm trúng giải độc đắc 136.8 tỷ. Đột nhiên An, người nắm giữ tấm vé bất ngờ gặp tai nạn không qua khỏi. Đứng trước món tiền trúng số đáng mơ ước lẽ ra sẽ dễ dàng có được trong tầm tay, nhóm bạn bước chân vào hành trình đi tìm tờ vé số. Nhưng đó chỉ là khởi đầu của vô số những sự kiện không ngờ đến. Liệu hành trình tìm kiếm và chia chác món tiền trong mơ béo bở này sẽ thực sự dẫn đưa cả nhóm đến đâu?'
    },
  ];
